// ─── ALL SERVICE DATA ───────────────────────────────────────────────

export const weddingData = {
  title: 'Wedding Photography',
  category: 'Wedding',
  tagline: '"Every love story is beautiful, but yours deserves to be told in the most extraordinary way."',
  color1: '#1B3A6B',
  color2: '#C9A84C',
  heroImage: '/images/gallery_wedding_1.png',
  stats: [
    { value: '300+', label: 'Weddings Captured' },
    { value: '8+', label: 'Years Experience' },
    { value: '100%', label: 'Client Satisfaction' },
    { value: '15+', label: 'Awards Won' },
  ],
  overviewTitle: 'Your Wedding, Immortalized Forever',
  overviewDesc: [
    'At Sanjari Production, we believe your wedding day is the most cinematic story of your life. Our wedding photography service is crafted with a blend of artistic vision, technical excellence, and heartfelt storytelling.',
    'From the intimate moments of getting ready to the grandeur of your reception, we capture every emotion, every glance, and every laugh — creating a visual legacy that you and your family will treasure for generations.',
    'Our team travels across Rajasthan and India, bringing our signature gold-and-blue cinematic aesthetic to every wedding we photograph.',
  ],
  includes: [
    { icon: '📸', label: 'Pre-Wedding Shoot', desc: 'Romantic couple session at a location of your choice' },
    { icon: '🎬', label: 'Full Day Coverage', desc: 'Complete coverage from Mehndi to Reception' },
    { icon: '✈️', label: 'Outstation Travel', desc: 'We travel anywhere in India for destination weddings' },
    { icon: '💿', label: 'High-Res Delivery', desc: '500+ edited photos delivered in digital album' },
    { icon: '📖', label: 'Premium Album', desc: 'Luxury hard-cover photo album included' },
    { icon: '🖼️', label: 'Canvas Prints', desc: '2 large canvas prints of your favourite shots' },
  ],
  process: [
    { icon: '☎️', title: 'Consultation', desc: 'We discuss your vision, style preferences, venues, and timeline.' },
    { icon: '📋', title: 'Planning', desc: 'Shot list creation, venue recce, and schedule preparation.' },
    { icon: '📷', title: 'Shoot Day', desc: 'Our team captures every magical moment seamlessly.' },
    { icon: '🎨', title: 'Editing', desc: 'Professional color grading and retouching within 30 days.' },
    { icon: '📦', title: 'Delivery', desc: 'Digital gallery + premium album delivered to your door.' },
  ],
  galleryImages: [
    '/images/gallery_wedding_1.png',
    '/images/gallery_wedding_2.png',
    '/images/gallery_portrait_1.png',
    '/images/gallery_cinematic_1.png',
  ],
  packages: [
    {
      name: 'Silver',
      price: '45,000',
      unit: '/event',
      featured: false,
      features: [
        '1 Photographer',
        '6 Hours Coverage',
        '250 Edited Photos',
        'Online Gallery',
        'Basic Retouching',
        '1 Month Delivery',
      ],
    },
    {
      name: 'Gold',
      price: '85,000',
      unit: '/event',
      featured: true,
      features: [
        '2 Photographers',
        'Full Day Coverage (12hrs)',
        '500+ Edited Photos',
        'Pre-Wedding Shoot',
        'Premium Retouching',
        'Luxury Photo Album',
        'Canvas Print (2x)',
        '30 Days Delivery',
      ],
    },
    {
      name: 'Platinum',
      price: '1,50,000',
      unit: '/event',
      featured: false,
      features: [
        '3 Photographers + 1 Videographer',
        '2-Day Coverage',
        '1000+ Edited Photos',
        'Drone Aerial Shots',
        'Cinematic Highlight Reel',
        'Luxury Flush Album',
        'Canvas Prints (4x)',
        'Priority 15-Day Delivery',
      ],
    },
  ],
};

export const videographyData = {
  title: 'Cinematic Videography',
  category: 'Videography',
  tagline: '"We don\'t just record moments — we craft films that move your soul."',
  color1: '#0D1F3C',
  color2: '#4A90D9',
  heroImage: '/images/gallery_cinematic_2.png',
  stats: [
    { value: '200+', label: 'Films Created' },
    { value: '4K', label: 'Resolution' },
    { value: '100%', label: 'Client Love' },
    { value: '10+', label: 'Film Awards' },
  ],
  overviewTitle: 'Storytelling Through the Art of Cinema',
  overviewDesc: [
    'Sanjari Production\'s cinematic videography service transforms your special events into breathtaking film productions. Using state-of-the-art cinema cameras, gimbals, and drones, we create videos that feel like they belong on the big screen.',
    'Our in-house post-production team handles color grading, sound design, and editing to deliver a final product that exceeds every expectation. Whether it\'s a wedding film, brand video, or documentary — we bring Hollywood-level production to every project.',
  ],
  includes: [
    { icon: '🎥', label: '4K Cinema Cameras', desc: 'Sony FX6, Blackmagic Cinema Line' },
    { icon: '🚁', label: 'Drone Aerial Footage', desc: 'DJI Mavic 3 Cine drone included' },
    { icon: '🎵', label: 'Custom Soundtrack', desc: 'Licensed music + sound design' },
    { icon: '🎨', label: 'Color Grading', desc: 'Professional DaVinci Resolve color grade' },
    { icon: '✂️', label: 'Cinematic Edit', desc: 'Narrative-driven cinematic cut' },
    { icon: '☁️', label: 'Online Delivery', desc: '4K delivery via private link' },
  ],
  process: [
    { icon: '🎭', title: 'Concept', desc: 'We develop a cinematic concept and storyboard for your film.' },
    { icon: '📷', title: 'Production', desc: 'Multi-camera shoots with drone, gimbal, and cinema rigs.' },
    { icon: '🎬', title: 'Post', desc: 'Professional editing, color grade, and sound design.' },
    { icon: '🔄', title: 'Review', desc: 'You review and request revisions. Up to 3 rounds included.' },
    { icon: '🎁', title: 'Delivery', desc: '4K film delivered digitally + USB keepsake.' },
  ],
  galleryImages: [
    '/images/gallery_cinematic_2.png',
    '/images/gallery_cinematic_1.png',
    '/images/gallery_wedding_1.png',
    '/images/gallery_portrait_2.png',
  ],
  packages: [
    {
      name: 'Short Film',
      price: '30,000',
      unit: '/project',
      featured: false,
      features: [
        '1 Videographer',
        '4 Hours Shoot',
        '3–5 Min Highlight Film',
        'Basic Color Grade',
        '1080p Delivery',
        '21 Days Delivery',
      ],
    },
    {
      name: 'Feature Film',
      price: '75,000',
      unit: '/project',
      featured: true,
      features: [
        '2 Videographers',
        'Full Day Shoot',
        '8–12 Min Cinematic Film',
        'Drone Footage',
        'Custom Music',
        '4K Color Grade',
        '4K Delivery + USB',
        '30 Days Delivery',
      ],
    },
    {
      name: 'Epic Film',
      price: '1,30,000',
      unit: '/project',
      featured: false,
      features: [
        '3 Videographers + Drone',
        'Multi-Day Shoot',
        '15–25 Min Documentary Film',
        'Aerial + Ground Coverage',
        'Original Score',
        'Cinema-Grade Post',
        '4K Delivery + Premium USB',
        'Priority 20-Day Delivery',
      ],
    },
  ],
};

export const portraitData = {
  title: 'Portrait Sessions',
  category: 'Portrait',
  tagline: '"Every face tells a story. We find the light that makes yours unforgettable."',
  color1: '#1a0a2e',
  color2: '#C9A84C',
  heroImage: '/images/gallery_portrait_1.png',
  stats: [
    { value: '1000+', label: 'Portraits Done' },
    { value: '2', label: 'Studio Locations' },
    { value: '100%', label: 'Satisfaction' },
    { value: '48hr', label: 'Quick Delivery' },
  ],
  overviewTitle: 'Portraits That Speak Without Words',
  overviewDesc: [
    'A great portrait goes beyond just a photograph — it\'s a window into someone\'s soul. Our portrait sessions are carefully crafted experiences that help you feel confident, comfortable, and truly yourself in front of the camera.',
    'Whether you need professional headshots, family portraits, a model portfolio, or a creative artistic shoot, our Jaipur studio and outdoor locations provide the perfect setting for every style of portrait photography.',
  ],
  includes: [
    { icon: '💡', label: 'Professional Lighting', desc: 'Studio strobes, beauty dishes, and natural light setups' },
    { icon: '👗', label: 'Styling Guidance', desc: 'Pre-shoot wardrobe and style consultation' },
    { icon: '🎨', label: 'Professional Retouching', desc: 'Skin retouching, blemish removal, and color grade' },
    { icon: '🏙️', label: 'Location Flexibility', desc: 'Studio or outdoor session, your choice' },
    { icon: '⚡', label: 'Same-Day Preview', desc: '10 preview shots delivered same day' },
    { icon: '💾', label: 'Digital Delivery', desc: 'High-res web + print versions' },
  ],
  process: [
    { icon: '💬', title: 'Consult', desc: 'Discuss your goals, style, wardrobe, and location.' },
    { icon: '👔', title: 'Prepare', desc: 'Styling tips, mood board, and shot list.' },
    { icon: '📸', title: 'Shoot', desc: 'Relaxed, guided session to bring out your best.' },
    { icon: '✏️', title: 'Retouch', desc: 'Careful professional retouching and color grade.' },
    { icon: '📤', title: 'Deliver', desc: 'Gallery ready within 48–72 hours.' },
  ],
  galleryImages: [
    '/images/gallery_portrait_1.png',
    '/images/gallery_portrait_2.png',
    '/images/gallery_fashion_1.png',
    '/images/gallery_fashion_2.png',
  ],
  packages: [
    {
      name: 'Mini',
      price: '5,000',
      unit: '/session',
      featured: false,
      features: [
        '1 Hour Session',
        '1 Location / 1 Outfit',
        '20 Edited Photos',
        'Basic Retouching',
        'Online Gallery',
        '5 Day Delivery',
      ],
    },
    {
      name: 'Classic',
      price: '12,000',
      unit: '/session',
      featured: true,
      features: [
        '3 Hour Session',
        '2 Locations / 3 Outfits',
        '60 Edited Photos',
        'Advanced Retouching',
        'Same-Day Previews (10)',
        'Online Gallery + USB',
        '3 Day Delivery',
      ],
    },
    {
      name: 'Signature',
      price: '22,000',
      unit: '/session',
      featured: false,
      features: [
        'Full Day Session (6hrs)',
        'Multiple Locations',
        '150+ Edited Photos',
        'Premium Retouching',
        'Hair & Makeup Coordination',
        'Printed Portraits (5x7, 3 pcs)',
        'Priority 48hr Delivery',
      ],
    },
  ],
};

export const corporateData = {
  title: 'Corporate Events',
  category: 'Corporate',
  tagline: '"Elevate your brand with imagery that commands attention and inspires confidence."',
  color1: '#0f1e3c',
  color2: '#2A5298',
  heroImage: '/images/gallery_corporate_1.png',
  stats: [
    { value: '150+', label: 'Brands Served' },
    { value: '500+', label: 'Events Covered' },
    { value: '24hr', label: 'Turnaround' },
    { value: '100%', label: 'Professional' },
  ],
  overviewTitle: 'Visual Content That Builds Brands',
  overviewDesc: [
    'In today\'s visual-first world, your brand imagery is your first impression. Sanjari Production\'s corporate photography and videography service helps businesses, startups, and enterprises create powerful visual content that communicates professionalism, trust, and vision.',
    'From product launches to executive portraits, annual conferences to brand films — we deliver corporate content that stands out in boardrooms and social media alike.',
  ],
  includes: [
    { icon: '🏢', label: 'Event Coverage', desc: 'Full corporate event, conference, or product launch coverage' },
    { icon: '👔', label: 'Executive Portraits', desc: 'Professional headshots for your leadership team' },
    { icon: '📱', label: 'Social Media Content', desc: 'Ready-to-post optimized images for all platforms' },
    { icon: '🎥', label: 'Brand Videos', desc: 'Corporate intro, testimonials, and promo videos' },
    { icon: '🛍️', label: 'Product Photography', desc: 'E-commerce and catalogue ready product shots' },
    { icon: '⚡', label: 'Fast Turnaround', desc: '24-48 hour delivery for urgent requirements' },
  ],
  process: [
    { icon: '📋', title: 'Brief', desc: 'Understanding your brand identity, goals, and requirements.' },
    { icon: '🗓️', title: 'Plan', desc: 'Shot list, schedule, and logistics coordination.' },
    { icon: '📸', title: 'Shoot', desc: 'Professional on-site coverage by our corporate team.' },
    { icon: '🎨', title: 'Edit', desc: 'Brand-consistent color grading and retouching.' },
    { icon: '📤', title: 'Deliver', desc: 'Web-ready and print-ready files within 24-48 hours.' },
  ],
  galleryImages: [
    '/images/gallery_corporate_1.png',
    '/images/gallery_portrait_2.png',
    '/images/gallery_cinematic_1.png',
    '/images/gallery_fashion_1.png',
  ],
  packages: [
    {
      name: 'Starter',
      price: '15,000',
      unit: '/day',
      featured: false,
      features: [
        '1 Photographer',
        '4 Hours Coverage',
        '100 Edited Photos',
        'Social Media Sizes',
        '48hr Delivery',
      ],
    },
    {
      name: 'Business',
      price: '35,000',
      unit: '/day',
      featured: true,
      features: [
        '2 Photographers',
        'Full Day Coverage',
        '300+ Edited Photos',
        'Headshots for Team (10)',
        'Brand Video (3 min)',
        'Social Media Pack',
        '24hr Delivery',
      ],
    },
    {
      name: 'Enterprise',
      price: '80,000',
      unit: '/project',
      featured: false,
      features: [
        '3-Person Team',
        'Multi-Day Coverage',
        '500+ Edited Photos',
        'Product Photography',
        'Brand Film (5 min)',
        'Drone B-Roll',
        'Priority 12hr Delivery',
      ],
    },
  ],
};

export const fashionData = {
  title: 'Fashion & Editorial',
  category: 'Fashion',
  tagline: '"Fashion is art. We are the canvas on which your vision comes alive."',
  color1: '#2D1B69',
  color2: '#C9A84C',
  heroImage: '/images/gallery_fashion_1.png',
  stats: [
    { value: '200+', label: 'Editorials Shot' },
    { value: '50+', label: 'Fashion Brands' },
    { value: '10+', label: 'Magazine Features' },
    { value: '100%', label: 'Trend-Forward' },
  ],
  overviewTitle: 'Where Fashion Meets Fine Art',
  overviewDesc: [
    'Sanjari Production\'s fashion and editorial photography brings together artistic vision, creative direction, and technical mastery to create images that define trends and tell bold visual stories.',
    'Whether you\'re a fashion brand launching a new collection, a model building your portfolio, or a magazine commissioning an editorial spread — our team delivers images that command attention, drive desire, and stand the test of time.',
  ],
  includes: [
    { icon: '💃', label: 'Creative Direction', desc: 'Full creative direction, mood boarding, and styling guidance' },
    { icon: '📖', label: 'Lookbook Production', desc: 'Complete seasonal lookbooks for brands and designers' },
    { icon: '🛍️', label: 'E-Commerce Shoots', desc: 'Clean, conversion-optimized product-on-model photography' },
    { icon: '✨', label: 'Magazine Editorial', desc: 'High-concept editorials for digital and print publications' },
    { icon: '👶', label: 'Model Portfolio', desc: 'Portfolio building shoots for aspiring models' },
    { icon: '🎨', label: 'Premium Retouching', desc: 'High-end skin retouching and compositing' },
  ],
  process: [
    { icon: '💡', title: 'Concept', desc: 'Creative direction, mood board, and concept development.' },
    { icon: '👗', title: 'Pre-Production', desc: 'Styling, model casting, location scouting, and HMU.' },
    { icon: '📸', title: 'Shoot', desc: 'High-energy shoot day with full creative team.' },
    { icon: '✏️', title: 'Post-Production', desc: 'High-end retouching, compositing, and color.' },
    { icon: '📦', title: 'Delivery', desc: 'Web, print, and social media ready files.' },
  ],
  galleryImages: [
    '/images/gallery_fashion_1.png',
    '/images/gallery_fashion_2.png',
    '/images/gallery_portrait_1.png',
    '/images/gallery_portrait_2.png',
  ],
  packages: [
    {
      name: 'Portfolio',
      price: '8,000',
      unit: '/session',
      featured: false,
      features: [
        '2 Hour Shoot',
        '2 Looks',
        '30 Edited Photos',
        'Basic Retouching',
        '5 Day Delivery',
      ],
    },
    {
      name: 'Lookbook',
      price: '45,000',
      unit: '/project',
      featured: true,
      features: [
        'Full Day Shoot',
        'Up to 8 Looks',
        '100 Edited Photos',
        'Creative Direction',
        'HMU Coordination',
        'High-End Retouching',
        '10 Day Delivery',
      ],
    },
    {
      name: 'Editorial',
      price: '90,000',
      unit: '/project',
      featured: false,
      features: [
        '2-Day Shoot',
        'Full Creative Team',
        '200+ Edited Photos',
        'Drone + Studio + Location',
        'Magazine-Quality Retouch',
        'Print + Digital Delivery',
        'Priority 7-Day Delivery',
      ],
    },
  ],
};

export const aerialData = {
  title: 'Aerial Drone Shots',
  category: 'Aerial',
  tagline: '"See the world from a perspective few ever experience — breathtaking, boundless, cinematic."',
  color1: '#0D2744',
  color2: '#6BA3BE',
  heroImage: '/images/gallery_cinematic_1.png',
  stats: [
    { value: '400+', label: 'Aerial Shoots' },
    { value: '4K', label: 'Drone Quality' },
    { value: '50+', label: 'Locations' },
    { value: 'FAA', label: 'Certified Pilots' },
  ],
  overviewTitle: 'Cinematic Perspectives From Above',
  overviewDesc: [
    'Our aerial drone photography and videography service adds a dimension of grandeur to any project. Using DJI Mavic 3 Cine and professional drone rigs, we capture sweeping aerial landscapes, architectural overviews, and dramatic event perspectives that simply cannot be achieved from the ground.',
    'Our DGCA-licensed drone pilots operate with the highest safety standards, ensuring smooth, legal, and stunning aerial content for weddings, real estate, corporate events, tourism, and more.',
  ],
  includes: [
    { icon: '🚁', label: 'DJI Cinema Drones', desc: 'DJI Mavic 3 Cine — 4K/120fps cinema-grade drone' },
    { icon: '📜', label: 'DGCA Licensed', desc: 'Fully licensed pilots compliant with Indian drone regulations' },
    { icon: '🗺️', label: 'Location Survey', desc: 'Pre-shoot location survey and flight path planning' },
    { icon: '🎨', label: 'Color Grade', desc: 'D-Log footage professionally color graded in post' },
    { icon: '🤝', label: 'Ground Team', desc: 'Ground crew and safety coordinators on-site' },
    { icon: '⚡', label: 'Quick Delivery', desc: 'Edited aerial footage within 3-5 business days' },
  ],
  process: [
    { icon: '📋', title: 'Plan', desc: 'Location survey, flight planning, and regulatory clearances.' },
    { icon: '🌤️', title: 'Weather Check', desc: 'Optimal weather window selection for best results.' },
    { icon: '🚁', title: 'Fly', desc: 'Professional drone operation for cinematic aerial shots.' },
    { icon: '🎨', title: 'Grade', desc: 'D-Log color grading for cinematic look.' },
    { icon: '📤', title: 'Deliver', desc: '4K footage delivered via cloud within 5 days.' },
  ],
  galleryImages: [
    '/images/gallery_cinematic_1.png',
    '/images/gallery_cinematic_2.png',
    '/images/gallery_wedding_1.png',
    '/images/gallery_corporate_1.png',
  ],
  packages: [
    {
      name: 'Basic Flight',
      price: '8,000',
      unit: '/hour',
      featured: false,
      features: [
        '1 Hour Flight Time',
        '4K Footage',
        '10 Aerial Photos',
        'Basic Edit',
        '5 Day Delivery',
      ],
    },
    {
      name: 'Cinematic',
      price: '20,000',
      unit: '/half day',
      featured: true,
      features: [
        '4 Hours Flight',
        '4K/60fps Footage',
        '30+ Aerial Photos',
        'D-Log Color Grade',
        'Highlight Reel (2 min)',
        'Ground Photography',
        '3 Day Delivery',
      ],
    },
    {
      name: 'Full Day Aerial',
      price: '40,000',
      unit: '/day',
      featured: false,
      features: [
        '8 Hours Coverage',
        '4K/120fps Cinema Drone',
        '60+ Aerial Photos',
        'Full Cinematic Edit',
        'Multiple Locations',
        'Ground + Aerial Combo',
        'Priority 2-Day Delivery',
      ],
    },
  ],
};
