// ─── ALL SERVICE DATA ───────────────────────────────────────────────

export const weddingData = {
  title: 'Wedding Photography & Films',
  category: 'Wedding',
  tagline: '"Every love story is beautiful, but yours deserves to be cinematic."',
  color1: '#1B3A6B',
  color2: '#C9A84C',
  heroImage: '/images/gallery_wedding_1.png',
  stats: [
    { value: '300+', label: 'Weddings Captured' },
    { value: '8+', label: 'Years Experience' },
    { value: '100%', label: 'Client Satisfaction' },
    { value: '15+', label: 'Awards Won' },
  ],
  overviewTitle: 'Your Wedding, Immortalized in Gold',
  overviewDesc: [
    'At Sanjari Production, we believe your wedding day is the most important cinematic story of your life. We do not just document events; we capture the soul, the grandeur, and the fleeting, unseen moments that make your story unique.',
    'Our wedding photography and filmmaking service is crafted with a blend of high-fashion artistic vision, technical excellence, and heartfelt storytelling. From the intimate chaos of getting ready to the epic scale of your reception, we shoot with a directorial eye — turning your reality into a masterpiece.',
    'We specialize in luxury destination weddings across India, bringing our signature gold-and-deep-blue cinematic aesthetic to every frame we capture.'
  ],
  equipment: [
    { icon: 'camera', name: 'Sony A1 & A7RV', desc: 'Flagship 50MP+ sensors for insane detail and dynamic range.' },
    { icon: 'lens', name: 'Sony G-Master Primes', desc: 'F1.2 & F1.4 lenses for that creamy, dreamy background blur.' },
    { icon: 'drone', name: 'DJI Mavic 3 Pro', desc: 'Triple-camera drone for sweeping, majestic venue shots.' },
    { icon: 'lighting', name: 'Profoto B10X', desc: 'Studio-quality off-camera flash for dramatic nighttime portraits.' }
  ],
  includes: [
    { icon: '/images/icons/camera.png', label: 'Pre-Wedding Shoot', desc: 'Romantic couple session at a location of your choice' },
    { icon: '/images/icons/cinema.png', label: 'Full Day Coverage', desc: 'Complete coverage from Mehndi to Reception' },
    { icon: '/images/icons/location.png', label: 'Outstation Travel', desc: 'We travel anywhere in India for destination weddings' },
    { icon: '/images/icons/digital.png', label: 'High-Res Delivery', desc: '500+ edited photos delivered in digital album' },
    { icon: '/images/icons/album.png', label: 'Premium Album', desc: 'Luxury hard-cover flush-mount photo album' },
    { icon: '/images/icons/album.png', label: 'Canvas Prints', desc: '2 large archival-quality canvas prints' },
  ],
  process: [
    { icon: '/images/icons/chat.png', title: 'Consultation', desc: 'We discuss your vision, style preferences, venues, and timeline.' },
    { icon: '/images/icons/chat.png', title: 'Planning', desc: 'Shot list creation, venue recce, and schedule preparation.' },
    { icon: '/images/icons/camera.png', title: 'Shoot Day', desc: 'Our team captures every magical moment seamlessly.' },
    { icon: '/images/icons/magic.png', title: 'Editing', desc: 'Professional color grading and retouching within 30 days.' },
    { icon: '/images/icons/digital.png', title: 'Delivery', desc: 'Digital gallery + premium album delivered to your door.' },
  ],
  galleryImages: [
    '/images/gallery_wedding_1.png',
    '/images/gallery_wedding_2.png',
    '/images/gallery_portrait_1.png',
    '/images/gallery_cinematic_1.png',
  ],
  packages: [
    {
      name: 'Silver',
      price: '45,000',
      unit: '/event',
      featured: false,
      features: [
        '1 Senior Photographer',
        '6 Hours Coverage',
        '250 Edited Photos',
        'Online Gallery',
        'Basic Retouching',
        '1 Month Delivery',
      ],
    },
    {
      name: 'Gold',
      price: '85,000',
      unit: '/event',
      featured: true,
      features: [
        '2 Senior Photographers',
        'Full Day Coverage (12hrs)',
        '500+ Edited Photos',
        'Pre-Wedding Shoot',
        'Premium Retouching',
        'Luxury Photo Album',
        'Canvas Print (2x)',
        '30 Days Delivery',
      ],
    },
    {
      name: 'Platinum',
      price: '1,50,000',
      unit: '/event',
      featured: false,
      features: [
        '3 Photographers + 1 Videographer',
        '2-Day Coverage',
        '1000+ Edited Photos',
        'Drone Aerial Shots',
        'Cinematic Highlight Reel',
        'Luxury Flush Album',
        'Canvas Prints (4x)',
        'Priority 15-Day Delivery',
      ],
    },
  ],
};

export const videographyData = {
  title: 'Cinematic Videography',
  category: 'Videography',
  tagline: '"We don\'t just record moments — we direct films that move your soul."',
  color1: '#0D1F3C',
  color2: '#4A90D9',
  heroImage: '/images/gallery_cinematic_2.png',
  stats: [
    { value: '200+', label: 'Films Created' },
    { value: '4K/8K', label: 'Resolution' },
    { value: '100%', label: 'Client Love' },
    { value: '10+', label: 'Film Awards' },
  ],
  overviewTitle: 'Hollywood-Level Production for Your Story',
  overviewDesc: [
    'Sanjari Production\'s cinematic videography transforms events, brands, and music into breathtaking film productions. We do not use standard video cameras; we shoot exclusively on Netflix-approved Cinema lines.',
    'Our approach involves meticulous storyboarding, motivated camera movement, and intricate sound design. In post-production, our DaVinci Resolve colorists craft a cinematic look that rivals modern feature films, ensuring your video feels grand, emotional, and timeless.',
  ],
  equipment: [
    { icon: 'video', name: 'Sony FX6 & RED Komodo', desc: 'True cinema cameras with incredible dynamic range and color science.' },
    { icon: 'stabilizer', name: 'DJI RS3 Pro Gimbal', desc: 'Heavy-duty stabilizers for buttery-smooth tracking shots.' },
    { icon: 'audio', name: 'Rode & Sennheiser Audio', desc: '32-bit float audio recorders so we never miss a whisper or a cheer.' },
    { icon: 'monitor', name: 'Atomos Ninja V', desc: 'Pro-res external monitoring for perfect exposure on set.' }
  ],
  includes: [
    { icon: '/images/icons/cinema.png', label: '4K Cinema Cameras', desc: 'Sony FX6, Blackmagic Cinema Line' },
    { icon: '/images/icons/aerial.png', label: 'Drone Aerial Footage', desc: 'DJI Mavic 3 Cine drone included' },
    { icon: '/images/icons/magic.png', label: 'Custom Soundtrack', desc: 'Licensed music + sound design' },
    { icon: '/images/icons/magic.png', label: 'Color Grading', desc: 'Professional DaVinci Resolve color grade' },
    { icon: '/images/icons/cinema.png', label: 'Cinematic Edit', desc: 'Narrative-driven cinematic cut' },
    { icon: '/images/icons/digital.png', label: 'Online Delivery', desc: '4K delivery via private link' },
  ],
  process: [
    { icon: '/images/icons/cinema.png', title: 'Concept', desc: 'We develop a cinematic concept and storyboard for your film.' },
    { icon: '/images/icons/camera.png', title: 'Production', desc: 'Multi-camera shoots with drone, gimbal, and cinema rigs.' },
    { icon: '/images/icons/cinema.png', title: 'Post', desc: 'Professional editing, color grade, and sound design.' },
    { icon: '/images/icons/digital.png', title: 'Review', desc: 'You review and request revisions. Up to 3 rounds included.' },
    { icon: '/images/icons/wedding.png', title: 'Delivery', desc: '4K film delivered digitally + USB keepsake.' },
  ],
  galleryImages: [
    '/images/gallery_cinematic_2.png',
    '/images/gallery_cinematic_1.png',
    '/images/gallery_wedding_1.png',
    '/images/gallery_portrait_2.png',
  ],
  packages: [
    {
      name: 'Short Film',
      price: '30,000',
      unit: '/project',
      featured: false,
      features: [
        '1 Videographer',
        '4 Hours Shoot',
        '3–5 Min Highlight Film',
        'Basic Color Grade',
        '1080p Delivery',
        '21 Days Delivery',
      ],
    },
    {
      name: 'Feature Film',
      price: '75,000',
      unit: '/project',
      featured: true,
      features: [
        '2 Videographers',
        'Full Day Shoot',
        '8–12 Min Cinematic Film',
        'Drone Footage',
        'Custom Music',
        '4K Color Grade',
        '4K Delivery + USB',
        '30 Days Delivery',
      ],
    },
    {
      name: 'Epic Film',
      price: '1,30,000',
      unit: '/project',
      featured: false,
      features: [
        '3 Videographers + Drone',
        'Multi-Day Shoot',
        '15–25 Min Documentary Film',
        'Aerial + Ground Coverage',
        'Original Score',
        'Cinema-Grade Post',
        '4K Delivery + Premium USB',
        'Priority 20-Day Delivery',
      ],
    },
  ],
};

export const portraitData = {
  title: 'Premium Portraiture',
  category: 'Portrait',
  tagline: '"Every face tells a story. We sculpt light to make yours unforgettable."',
  color1: '#1a0a2e',
  color2: '#C9A84C',
  heroImage: '/images/gallery_portrait_1.png',
  stats: [
    { value: '1000+', label: 'Portraits Done' },
    { value: '2', label: 'Studio Locations' },
    { value: '100%', label: 'Satisfaction' },
    { value: '48hr', label: 'Quick Delivery' },
  ],
  overviewTitle: 'Portraits That Speak Without Words',
  overviewDesc: [
    'A great portrait goes beyond just a photograph — it\'s a window into someone\'s soul. Our premium portrait sessions are carefully crafted experiences that help you feel confident, powerful, and truly yourself in front of the lens.',
    'We employ high-end editorial lighting techniques used by top fashion magazines to sculpt your features. Whether you need professional executive headshots, a creative model portfolio, or intimate fine-art portraits, we deliver imagery that demands attention.',
  ],
  equipment: [
    { icon: 'camera', name: 'Sony A7RV (61MP)', desc: 'Ultra-high resolution for flawless skin texture and detail.' },
    { icon: 'lighting', name: 'Profoto Pro-11', desc: 'The world\'s fastest and most consistent studio strobes.' },
    { icon: 'lens', name: 'Sony 85mm f/1.4 GM', desc: 'The ultimate portrait lens for stunning subject isolation.' },
    { icon: 'monitor', name: 'Capture One Tethering', desc: 'Real-time tethered shooting so you can see results instantly on a large screen.' }
  ],
  includes: [
    { icon: '/images/icons/magic.png', label: 'Professional Lighting', desc: 'Studio strobes, beauty dishes, and natural light setups' },
    { icon: '/images/icons/fashion.png', label: 'Styling Guidance', desc: 'Pre-shoot wardrobe and style consultation' },
    { icon: '/images/icons/magic.png', label: 'Professional Retouching', desc: 'Skin retouching, blemish removal, and color grade' },
    { icon: '/images/icons/location.png', label: 'Location Flexibility', desc: 'Studio or outdoor session, your choice' },
    { icon: '/images/icons/magic.png', label: 'Same-Day Preview', desc: '10 preview shots delivered same day' },
    { icon: '/images/icons/digital.png', label: 'Digital Delivery', desc: 'High-res web + print versions' },
  ],
  process: [
    { icon: '/images/icons/chat.png', title: 'Consult', desc: 'Discuss your goals, style, wardrobe, and location.' },
    { icon: '/images/icons/corporate.png', title: 'Prepare', desc: 'Styling tips, mood board, and shot list.' },
    { icon: '/images/icons/camera.png', title: 'Shoot', desc: 'Relaxed, guided session to bring out your best.' },
    { icon: '/images/icons/magic.png', title: 'Retouch', desc: 'Careful professional retouching and color grade.' },
    { icon: '/images/icons/digital.png', title: 'Deliver', desc: 'Gallery ready within 48–72 hours.' },
  ],
  galleryImages: [
    '/images/gallery_portrait_1.png',
    '/images/gallery_portrait_2.png',
    '/images/gallery_fashion_1.png',
    '/images/gallery_fashion_2.png',
  ],
  packages: [
    {
      name: 'Mini',
      price: '5,000',
      unit: '/session',
      featured: false,
      features: [
        '1 Hour Session',
        '1 Location / 1 Outfit',
        '20 Edited Photos',
        'Basic Retouching',
        'Online Gallery',
        '5 Day Delivery',
      ],
    },
    {
      name: 'Classic',
      price: '12,000',
      unit: '/session',
      featured: true,
      features: [
        '3 Hour Session',
        '2 Locations / 3 Outfits',
        '60 Edited Photos',
        'Advanced Retouching',
        'Same-Day Previews (10)',
        'Online Gallery + USB',
        '3 Day Delivery',
      ],
    },
    {
      name: 'Signature',
      price: '22,000',
      unit: '/session',
      featured: false,
      features: [
        'Full Day Session (6hrs)',
        'Multiple Locations',
        '150+ Edited Photos',
        'Premium Retouching',
        'Hair & Makeup Coordination',
        'Printed Portraits (5x7, 3 pcs)',
        'Priority 48hr Delivery',
      ],
    },
  ],
};

export const corporateData = {
  title: 'Corporate & Brand Identity',
  category: 'Corporate',
  tagline: '"Elevate your brand with imagery that commands authority and inspires trust."',
  color1: '#0f1e3c',
  color2: '#2A5298',
  heroImage: '/images/gallery_corporate_1.png',
  stats: [
    { value: '150+', label: 'Brands Served' },
    { value: '500+', label: 'Events Covered' },
    { value: '24hr', label: 'Turnaround' },
    { value: '100%', label: 'Professional' },
  ],
  overviewTitle: 'Visual Content That Builds Brands',
  overviewDesc: [
    'In today\'s visual-first world, your brand imagery is your first impression. Sanjari Production\'s corporate photography helps businesses, startups, and enterprises create powerful visual content that communicates professionalism and vision.',
    'From dynamic product launches and high-stakes conferences to polished executive portraits and brand films — we deliver corporate content that stands out in boardrooms, annual reports, and social media campaigns alike.',
  ],
  equipment: [
    { icon: 'camera', name: 'Dual Sony A7IV Setup', desc: 'Fast, reliable, and unobtrusive cameras for corporate events.' },
    { icon: 'lens', name: '70-200mm f/2.8 GM II', desc: 'Allows us to capture speakers and guests from a distance without interrupting.' },
    { icon: 'lighting', name: 'Portable Softboxes', desc: 'Quick-setup studio lighting for on-location executive headshots.' },
    { icon: 'monitor', name: 'Instant Delivery Tech', desc: 'On-site photo transfer capabilities for live social media updates.' }
  ],
  includes: [
    { icon: '/images/icons/location.png', label: 'Event Coverage', desc: 'Full corporate event, conference, or product launch coverage' },
    { icon: '/images/icons/corporate.png', label: 'Executive Portraits', desc: 'Professional headshots for your leadership team' },
    { icon: '📱', label: 'Social Media Content', desc: 'Ready-to-post optimized images for all platforms' },
    { icon: '/images/icons/cinema.png', label: 'Brand Videos', desc: 'Corporate intro, testimonials, and promo videos' },
    { icon: '/images/icons/fashion.png', label: 'Product Photography', desc: 'E-commerce and catalogue ready product shots' },
    { icon: '/images/icons/magic.png', label: 'Fast Turnaround', desc: '24-48 hour delivery for urgent requirements' },
  ],
  process: [
    { icon: '/images/icons/chat.png', title: 'Brief', desc: 'Understanding your brand identity, goals, and requirements.' },
    { icon: '/images/icons/chat.png', title: 'Plan', desc: 'Shot list, schedule, and logistics coordination.' },
    { icon: '/images/icons/camera.png', title: 'Shoot', desc: 'Professional on-site coverage by our corporate team.' },
    { icon: '/images/icons/magic.png', title: 'Edit', desc: 'Brand-consistent color grading and retouching.' },
    { icon: '/images/icons/digital.png', title: 'Deliver', desc: 'Web-ready and print-ready files within 24-48 hours.' },
  ],
  galleryImages: [
    '/images/gallery_corporate_1.png',
    '/images/gallery_portrait_2.png',
    '/images/gallery_cinematic_1.png',
    '/images/gallery_fashion_1.png',
  ],
  packages: [
    {
      name: 'Starter',
      price: '15,000',
      unit: '/day',
      featured: false,
      features: [
        '1 Photographer',
        '4 Hours Coverage',
        '100 Edited Photos',
        'Social Media Sizes',
        '48hr Delivery',
      ],
    },
    {
      name: 'Business',
      price: '35,000',
      unit: '/day',
      featured: true,
      features: [
        '2 Photographers',
        'Full Day Coverage',
        '300+ Edited Photos',
        'Headshots for Team (10)',
        'Brand Video (3 min)',
        'Social Media Pack',
        '24hr Delivery',
      ],
    },
    {
      name: 'Enterprise',
      price: '80,000',
      unit: '/project',
      featured: false,
      features: [
        '3-Person Team',
        'Multi-Day Coverage',
        '500+ Edited Photos',
        'Product Photography',
        'Brand Film (5 min)',
        'Drone B-Roll',
        'Priority 12hr Delivery',
      ],
    },
  ],
};

export const fashionData = {
  title: 'Fashion & Editorial',
  category: 'Fashion',
  tagline: '"Fashion is art. We are the canvas on which your vision comes alive."',
  color1: '#2D1B69',
  color2: '#C9A84C',
  heroImage: '/images/gallery_fashion_1.png',
  stats: [
    { value: '200+', label: 'Editorials Shot' },
    { value: '50+', label: 'Fashion Brands' },
    { value: '10+', label: 'Magazine Features' },
    { value: '100%', label: 'Trend-Forward' },
  ],
  overviewTitle: 'Where Fashion Meets Fine Art',
  overviewDesc: [
    'Sanjari Production\'s fashion and editorial photography brings together artistic vision, creative direction, and technical mastery to create images that define trends and tell bold visual stories.',
    'Whether you\'re a fashion brand launching a new collection, a model building a high-impact portfolio, or a magazine commissioning an editorial spread — our team delivers imagery with perfect skin tones, immaculate lighting, and high-fashion aesthetics.',
  ],
  equipment: [
    { icon: 'camera', name: 'Medium Format Systems', desc: 'Unparalleled color depth and detail for commercial print campaigns.' },
    { icon: 'lighting', name: 'Broncolor Paras', desc: 'The gold standard in fashion lighting for that signature editorial look.' },
    { icon: 'lens', name: 'Tethered Workstations', desc: 'Live viewing with Capture One for art directors and stylists on set.' },
    { icon: 'monitor', name: 'Color-Calibrated Monitors', desc: 'Eizo monitors ensuring 100% accurate color reproduction for garments.' }
  ],
  includes: [
    { icon: '/images/icons/fashion.png', label: 'Creative Direction', desc: 'Full creative direction, mood boarding, and styling guidance' },
    { icon: '/images/icons/album.png', label: 'Lookbook Production', desc: 'Complete seasonal lookbooks for brands and designers' },
    { icon: '/images/icons/fashion.png', label: 'E-Commerce Shoots', desc: 'Clean, conversion-optimized product-on-model photography' },
    { icon: '/images/icons/magic.png', label: 'Magazine Editorial', desc: 'High-concept editorials for digital and print publications' },
    { icon: '/images/icons/portrait.png', label: 'Model Portfolio', desc: 'Portfolio building shoots for aspiring models' },
    { icon: '/images/icons/magic.png', label: 'Premium Retouching', desc: 'High-end skin retouching and compositing' },
  ],
  process: [
    { icon: '/images/icons/magic.png', title: 'Concept', desc: 'Creative direction, mood board, and concept development.' },
    { icon: '/images/icons/fashion.png', title: 'Pre-Production', desc: 'Styling, model casting, location scouting, and HMU.' },
    { icon: '/images/icons/camera.png', title: 'Shoot', desc: 'High-energy shoot day with full creative team.' },
    { icon: '/images/icons/magic.png', title: 'Post-Production', desc: 'High-end retouching, frequency separation, and color grading.' },
    { icon: '/images/icons/digital.png', title: 'Delivery', desc: 'Web, print, and billboard-ready TIFF files.' },
  ],
  galleryImages: [
    '/images/gallery_fashion_1.png',
    '/images/gallery_fashion_2.png',
    '/images/gallery_portrait_1.png',
    '/images/gallery_portrait_2.png',
  ],
  packages: [
    {
      name: 'Portfolio',
      price: '8,000',
      unit: '/session',
      featured: false,
      features: [
        '2 Hour Shoot',
        '2 Looks',
        '30 Edited Photos',
        'Basic Retouching',
        '5 Day Delivery',
      ],
    },
    {
      name: 'Lookbook',
      price: '45,000',
      unit: '/project',
      featured: true,
      features: [
        'Full Day Shoot',
        'Up to 8 Looks',
        '100 Edited Photos',
        'Creative Direction',
        'HMU Coordination',
        'High-End Retouching',
        '10 Day Delivery',
      ],
    },
    {
      name: 'Editorial',
      price: '90,000',
      unit: '/project',
      featured: false,
      features: [
        '2-Day Shoot',
        'Full Creative Team',
        '200+ Edited Photos',
        'Drone + Studio + Location',
        'Magazine-Quality Retouch',
        'Print + Digital Delivery',
        'Priority 7-Day Delivery',
      ],
    },
  ],
};

export const aerialData = {
  title: 'Cinematic Aerial Drone',
  category: 'Aerial',
  tagline: '"See the world from a perspective few ever experience — breathtaking, boundless, cinematic."',
  color1: '#0D2744',
  color2: '#6BA3BE',
  heroImage: '/images/gallery_cinematic_1.png',
  stats: [
    { value: '400+', label: 'Aerial Shoots' },
    { value: '5.1K', label: 'Drone Quality' },
    { value: '50+', label: 'Locations' },
    { value: 'DGCA', label: 'Certified Pilots' },
  ],
  overviewTitle: 'Cinematic Perspectives From Above',
  overviewDesc: [
    'Our aerial drone photography and videography service adds a dimension of grandeur to any project. We capture sweeping aerial landscapes, architectural overviews, and dramatic event perspectives that simply cannot be achieved from the ground.',
    'Our DGCA-licensed drone pilots operate with the highest safety standards, ensuring smooth, legal, and stunning aerial content for weddings, real estate, corporate events, tourism, and cinema production.',
  ],
  equipment: [
    { icon: 'drone', name: 'DJI Inspire 3 & Mavic 3 Cine', desc: 'Hollywood-grade heavy-lift and agile drones recording in 5.1K Apple ProRes.' },
    { icon: 'video', name: 'ND/PL Filters', desc: 'Professional cinema filters to maintain perfect shutter speed and remove glare.' },
    { icon: 'monitor', name: 'DJI RC Pro', desc: 'Ultra-bright remote controllers for precise monitoring even in harsh sunlight.' },
    { icon: 'stabilizer', name: 'Advanced ActiveTrack', desc: 'AI-assisted subject tracking for high-speed action and vehicle follows.' }
  ],
  includes: [
    { icon: '/images/icons/aerial.png', label: 'DJI Cinema Drones', desc: 'DJI Mavic 3 Cine — 4K/120fps cinema-grade drone' },
    { icon: '/images/icons/album.png', label: 'DGCA Licensed', desc: 'Fully licensed pilots compliant with Indian drone regulations' },
    { icon: '/images/icons/location.png', label: 'Location Survey', desc: 'Pre-shoot location survey and flight path planning' },
    { icon: '/images/icons/magic.png', label: 'Color Grade', desc: 'D-Log footage professionally color graded in post' },
    { icon: '/images/icons/chat.png', label: 'Ground Team', desc: 'Ground crew and safety coordinators on-site' },
    { icon: '/images/icons/magic.png', label: 'Quick Delivery', desc: 'Edited aerial footage within 3-5 business days' },
  ],
  process: [
    { icon: '/images/icons/chat.png', title: 'Plan', desc: 'Location survey, flight planning, and regulatory clearances.' },
    { icon: '/images/icons/location.png', title: 'Weather Check', desc: 'Optimal weather window selection for best results.' },
    { icon: '/images/icons/aerial.png', title: 'Fly', desc: 'Professional drone operation for cinematic aerial shots.' },
    { icon: '/images/icons/magic.png', title: 'Grade', desc: 'D-Log color grading for cinematic look.' },
    { icon: '/images/icons/digital.png', title: 'Deliver', desc: '4K/5K footage delivered via cloud within 5 days.' },
  ],
  galleryImages: [
    '/images/gallery_cinematic_1.png',
    '/images/gallery_cinematic_2.png',
    '/images/gallery_wedding_1.png',
    '/images/gallery_corporate_1.png',
  ],
  packages: [
    {
      name: 'Basic Flight',
      price: '8,000',
      unit: '/hour',
      featured: false,
      features: [
        '1 Hour Flight Time',
        '4K Footage',
        '10 Aerial Photos',
        'Basic Edit',
        '5 Day Delivery',
      ],
    },
    {
      name: 'Cinematic',
      price: '20,000',
      unit: '/half day',
      featured: true,
      features: [
        '4 Hours Flight',
        '4K/60fps Footage',
        '30+ Aerial Photos',
        'D-Log Color Grade',
        'Highlight Reel (2 min)',
        'Ground Photography',
        '3 Day Delivery',
      ],
    },
    {
      name: 'Full Day Aerial',
      price: '40,000',
      unit: '/day',
      featured: false,
      features: [
        '8 Hours Coverage',
        '5.1K Cinema Drone',
        '60+ Aerial Photos',
        'Full Cinematic Edit',
        'Multiple Locations',
        'Ground + Aerial Combo',
        'Priority 2-Day Delivery',
      ],
    },
  ],
};
